2019-12-06 14:32:38,154 primer_db.views INFO     Data submitted by scientist:
2019-12-06 14:32:38,184 primer_db.views INFO     Submitting primer
2019-12-06 14:32:38,355 primer_db.views INFO     Common info for primers:
2019-12-06 14:32:38,358 primer_db.views INFO     Pair created, id: 1401
2019-12-06 14:32:38,361 primer_db.views INFO     Scientist submitting primer: Mr Man
2019-12-06 14:32:38,362 primer_db.views INFO     Using pcr program: TD65_55
2019-12-06 14:32:38,364 primer_db.views INFO     Using buffer: Buffer D
2019-12-06 14:32:38,365 primer_db.views INFO     Data for primer1:
2019-12-06 14:32:38,369 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:32:38,588 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:32:38,598 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:32:38,781 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:32:38,787 primer_db.views INFO     SNPs detected in primer
2019-12-06 14:32:38,788 primer_db.views INFO     Status of primer: On order
2019-12-06 14:32:38,791 primer_db.views INFO     Using coordinates: 6 26093094 26093114 26092866 26092886
2019-12-06 14:32:38,793 primer_db.views INFO     Created primer: 2279 HFE_test_f2
2019-12-06 14:32:38,794 primer_db.views INFO     Primer gene: HFE
2019-12-06 14:32:38,794 primer_db.views INFO     Primer sequence: CTGGATAACCTTGGCTGTAC
2019-12-06 14:32:38,794 primer_db.views INFO     Primer gc %: 50.0
2019-12-06 14:32:38,794 primer_db.views INFO     Primer tm: 55.533590
2019-12-06 14:32:38,795 primer_db.views INFO     Data for primer2
2019-12-06 14:32:38,799 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:32:38,998 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:32:39,006 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:32:39,289 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:32:39,293 primer_db.views INFO     SNPs detected in primer
2019-12-06 14:32:39,295 primer_db.views INFO     Status of primer2: On order
2019-12-06 14:32:39,300 primer_db.views INFO     New coordinates added to db: 6 26093181 26093200 26092953 26092972
2019-12-06 14:32:39,302 primer_db.views INFO     Created primer: 2280 HFE_test_r2
2019-12-06 14:32:39,303 primer_db.views INFO     Primer gene: HFE
2019-12-06 14:32:39,304 primer_db.views INFO     Primer sequence: TCAGTCACATACCCCAGAT
2019-12-06 14:32:39,306 primer_db.views INFO     Primer gc %: 47.37
2019-12-06 14:32:39,306 primer_db.views INFO     Primer tm: 54.626734
2019-12-06 14:34:48,977 primer_db.views INFO     Data submitted by scientist:
2019-12-06 14:34:49,003 primer_db.views INFO     Submitting primer
2019-12-06 14:34:49,177 primer_db.views INFO     Common info for primers:
2019-12-06 14:34:49,181 primer_db.views INFO     Pair created, id: 1402
2019-12-06 14:34:49,184 primer_db.views INFO     Scientist submitting primer: Mr Man
2019-12-06 14:34:49,186 primer_db.views INFO     Using pcr program: TD65_55
2019-12-06 14:34:49,187 primer_db.views INFO     Using buffer: Buffer D
2019-12-06 14:34:49,188 primer_db.views INFO     Data for primer1:
2019-12-06 14:34:49,193 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:34:49,722 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:34:49,746 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:34:49,923 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:34:49,930 primer_db.views INFO     SNPs detected in primer
2019-12-06 14:34:49,932 primer_db.views INFO     Status of primer: On order
2019-12-06 14:34:49,962 primer_db.views INFO     Using coordinates: 6 26093094 26093114 26092866 26092886
2019-12-06 14:34:49,995 primer_db.views INFO     Created primer: 2281 HFE_test_f3
2019-12-06 14:34:49,995 primer_db.views INFO     Primer gene: HFE
2019-12-06 14:34:49,995 primer_db.views INFO     Primer sequence: CTGGATAACCTTGGCTGTAC
2019-12-06 14:34:49,995 primer_db.views INFO     Primer gc %: 50.0
2019-12-06 14:34:49,996 primer_db.views INFO     Primer tm: 55.533590
2019-12-06 14:34:49,997 primer_db.views INFO     Data for primer2
2019-12-06 14:34:50,000 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:34:50,200 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:34:50,211 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:34:50,389 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:34:50,394 primer_db.views INFO     SNPs detected in primer
2019-12-06 14:34:50,396 primer_db.views INFO     Status of primer2: On order
2019-12-06 14:34:50,399 primer_db.views INFO     Using coordinates: 6 26093181 26093200 26092953 26092972
2019-12-06 14:34:50,401 primer_db.views INFO     Created primer: 2282 HFE_test_r3
2019-12-06 14:34:50,401 primer_db.views INFO     Primer gene: HFE
2019-12-06 14:34:50,401 primer_db.views INFO     Primer sequence: TCAGTCACATACCCCAGAT
2019-12-06 14:34:50,401 primer_db.views INFO     Primer gc %: 47.37
2019-12-06 14:34:50,401 primer_db.views INFO     Primer tm: 54.626734
2019-12-06 14:34:50,402 django.request ERROR    Internal Server Error: /primer_db/submit_pair/
Traceback (most recent call last):
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/storage/home/rainfoj/Projects/genetics_ark_django/primer_db/views.py", line 767, in submit_pair
    multiple_mapping(sequence1, sequence2, chrom)
NameError: name 'chrom' is not defined
2019-12-06 14:35:50,468 primer_db.views INFO     Data submitted by scientist:
2019-12-06 14:35:50,497 primer_db.views INFO     Submitting primer
2019-12-06 14:35:50,705 primer_db.views INFO     Common info for primers:
2019-12-06 14:35:50,709 primer_db.views INFO     Pair created, id: 1403
2019-12-06 14:35:50,719 primer_db.views INFO     Scientist submitting primer: Mr Man
2019-12-06 14:35:50,720 primer_db.views INFO     Using pcr program: TD65_55
2019-12-06 14:35:50,722 primer_db.views INFO     Using buffer: Buffer D
2019-12-06 14:35:50,742 primer_db.views INFO     Data for primer1:
2019-12-06 14:35:50,749 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:35:50,996 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:35:51,005 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:35:51,205 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:35:51,213 primer_db.views INFO     SNPs detected in primer
2019-12-06 14:35:51,223 primer_db.views INFO     Status of primer: On order
2019-12-06 14:35:51,226 primer_db.views INFO     Using coordinates: 6 26093094 26093114 26092866 26092886
2019-12-06 14:35:51,229 django.request ERROR    Internal Server Error: /primer_db/submit_pair/
Traceback (most recent call last):
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/mnt/storage/home/kimy/software/miniconda3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/mnt/storage/home/kimy/software/miniconda3/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/mnt/storage/home/kimy/software/miniconda3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/mnt/storage/home/kimy/software/miniconda3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/mnt/storage/home/kimy/software/miniconda3/lib/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.IntegrityError: (1062, "Duplicate entry 'HFE_test_f3' for key 'name'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/storage/home/rainfoj/Projects/genetics_ark_django/primer_db/views.py", line 709, in submit_pair
    snp_status = snp_status1, snp_info = ";".join(snp_info1), snp_date = snp_date1
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/db/models/base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/db/models/base.py", line 837, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/db/models/base.py", line 923, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/db/models/base.py", line 962, in _do_insert
    using=using, raw=raw)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1107, in execute_sql
    cursor.execute(sql, params)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/mnt/storage/home/kimy/software/miniconda3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/mnt/storage/home/kimy/software/miniconda3/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/mnt/storage/home/kimy/software/miniconda3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/mnt/storage/home/kimy/software/miniconda3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/mnt/storage/home/kimy/software/miniconda3/lib/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1062, "Duplicate entry 'HFE_test_f3' for key 'name'")
2019-12-06 14:36:00,304 primer_db.views INFO     Data submitted by scientist:
2019-12-06 14:36:00,327 primer_db.views INFO     Submitting primer
2019-12-06 14:36:00,518 primer_db.views INFO     Common info for primers:
2019-12-06 14:36:00,521 primer_db.views INFO     Pair created, id: 1404
2019-12-06 14:36:00,524 primer_db.views INFO     Scientist submitting primer: Mr Man
2019-12-06 14:36:00,525 primer_db.views INFO     Using pcr program: TD65_55
2019-12-06 14:36:00,541 primer_db.views INFO     Using buffer: Buffer D
2019-12-06 14:36:00,541 primer_db.views INFO     Data for primer1:
2019-12-06 14:36:00,544 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:36:00,743 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:36:00,751 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:36:00,927 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:36:00,931 primer_db.views INFO     SNPs detected in primer
2019-12-06 14:36:00,933 primer_db.views INFO     Status of primer: On order
2019-12-06 14:36:00,953 primer_db.views INFO     Using coordinates: 6 26093094 26093114 26092866 26092886
2019-12-06 14:36:00,955 primer_db.views INFO     Created primer: 2284 HFE_test_f4
2019-12-06 14:36:00,956 primer_db.views INFO     Primer gene: HFE
2019-12-06 14:36:00,956 primer_db.views INFO     Primer sequence: CTGGATAACCTTGGCTGTAC
2019-12-06 14:36:00,956 primer_db.views INFO     Primer gc %: 50.0
2019-12-06 14:36:00,956 primer_db.views INFO     Primer tm: 55.533590
2019-12-06 14:36:00,956 primer_db.views INFO     Data for primer2
2019-12-06 14:36:00,960 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:36:01,148 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:36:01,160 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:36:01,346 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:36:01,351 primer_db.views INFO     SNPs detected in primer
2019-12-06 14:36:01,374 primer_db.views INFO     Status of primer2: On order
2019-12-06 14:36:01,377 primer_db.views INFO     Using coordinates: 6 26093181 26093200 26092953 26092972
2019-12-06 14:36:01,384 primer_db.views INFO     Created primer: 2285 HFE_test_r4
2019-12-06 14:36:01,390 primer_db.views INFO     Primer gene: HFE
2019-12-06 14:36:01,428 primer_db.views INFO     Primer sequence: TCAGTCACATACCCCAGAT
2019-12-06 14:36:01,429 primer_db.views INFO     Primer gc %: 47.37
2019-12-06 14:36:01,429 primer_db.views INFO     Primer tm: 54.626734
2019-12-06 14:36:01,430 django.request ERROR    Internal Server Error: /primer_db/submit_pair/
Traceback (most recent call last):
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/storage/home/rainfoj/Projects/genetics_ark_django/primer_db/views.py", line 767, in submit_pair
    multiple_mapping(sequence1, sequence2, gene_chrom)
  File "/mnt/storage/home/rainfoj/Projects/genetics_ark_django/primer_db/views.py", line 98, in multiple_mapping
    primer_fasta.write(">{}\n{}\n".format("f"), sequence1.strip())
IndexError: tuple index out of range
2019-12-06 14:38:34,243 primer_db.views INFO     Data submitted by scientist:
2019-12-06 14:38:34,271 primer_db.views INFO     Submitting primer
2019-12-06 14:38:34,442 primer_db.views INFO     Common info for primers:
2019-12-06 14:38:34,446 primer_db.views INFO     Pair created, id: 1405
2019-12-06 14:38:34,451 primer_db.views INFO     Scientist submitting primer: Mr Man
2019-12-06 14:38:34,453 primer_db.views INFO     Using pcr program: TD65_55
2019-12-06 14:38:34,461 primer_db.views INFO     Using buffer: Buffer D
2019-12-06 14:38:34,468 primer_db.views INFO     Data for primer1:
2019-12-06 14:38:34,481 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:38:34,684 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:38:34,702 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:38:34,878 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:38:34,882 primer_db.views INFO     SNPs detected in primer
2019-12-06 14:38:34,884 primer_db.views INFO     Status of primer: On order
2019-12-06 14:38:34,887 primer_db.views INFO     Using coordinates: 6 26093094 26093114 26092866 26092886
2019-12-06 14:38:34,896 primer_db.views INFO     Created primer: 2286 HFE_test_f5
2019-12-06 14:38:34,902 primer_db.views INFO     Primer gene: HFE
2019-12-06 14:38:34,910 primer_db.views INFO     Primer sequence: CTGGATAACCTTGGCTGTAC
2019-12-06 14:38:34,918 primer_db.views INFO     Primer gc %: 50.0
2019-12-06 14:38:34,926 primer_db.views INFO     Primer tm: 55.533590
2019-12-06 14:38:34,940 primer_db.views INFO     Data for primer2
2019-12-06 14:38:34,945 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:38:35,153 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:38:35,164 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:38:35,351 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:38:35,356 primer_db.views INFO     SNPs detected in primer
2019-12-06 14:38:35,357 primer_db.views INFO     Status of primer2: On order
2019-12-06 14:38:35,360 primer_db.views INFO     Using coordinates: 6 26093181 26093200 26092953 26092972
2019-12-06 14:38:35,362 primer_db.views INFO     Created primer: 2287 HFE_test_r5
2019-12-06 14:38:35,362 primer_db.views INFO     Primer gene: HFE
2019-12-06 14:38:35,362 primer_db.views INFO     Primer sequence: TCAGTCACATACCCCAGAT
2019-12-06 14:38:35,362 primer_db.views INFO     Primer gc %: 47.37
2019-12-06 14:38:35,362 primer_db.views INFO     Primer tm: 54.626734
2019-12-06 14:38:35,373 django.request ERROR    Internal Server Error: /primer_db/submit_pair/
Traceback (most recent call last):
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/storage/home/rainfoj/Projects/genetics_ark_django/primer_db/views.py", line 764, in submit_pair
    multiple_mapping(sequence1, sequence2, gene_chrom)
  File "/mnt/storage/home/rainfoj/Projects/genetics_ark_django/primer_db/views.py", line 119, in multiple_mapping
    if gene_chrom == line[2]:
IndexError: list index out of range
2019-12-06 14:40:42,008 primer_db.views INFO     Data submitted by scientist:
2019-12-06 14:40:42,040 primer_db.views INFO     Submitting primer
2019-12-06 14:40:42,300 primer_db.views INFO     Common info for primers:
2019-12-06 14:40:42,305 primer_db.views INFO     Pair created, id: 1406
2019-12-06 14:40:42,309 primer_db.views INFO     New scientist added to db: Mr Angry
2019-12-06 14:40:42,315 primer_db.views INFO     Using pcr program: TD65_55
2019-12-06 14:40:42,316 primer_db.views INFO     Using buffer: Buffer D
2019-12-06 14:40:42,317 primer_db.views INFO     Data for primer1:
2019-12-06 14:40:42,322 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:40:42,520 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:40:42,528 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:40:43,167 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:40:43,171 primer_db.views INFO     No SNPs detected in primer
2019-12-06 14:40:43,173 primer_db.views INFO     Status of primer: On order
2019-12-06 14:40:43,177 primer_db.views INFO     New coordinates added to db: 19 35773330 35773350 35282427 35282447
2019-12-06 14:40:43,180 primer_db.views INFO     Created primer: 2288 hamp_test_f
2019-12-06 14:40:43,180 primer_db.views INFO     Primer gene: HAMP
2019-12-06 14:40:43,180 primer_db.views INFO     Primer sequence: CCACCACCTTCTTGGAAATG
2019-12-06 14:40:43,181 primer_db.views INFO     Primer gc %: 50.0
2019-12-06 14:40:43,183 primer_db.views INFO     Primer tm: 56.596388
2019-12-06 14:40:43,183 primer_db.views INFO     Data for primer2
2019-12-06 14:40:43,186 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:40:43,365 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:40:43,374 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:40:43,555 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:40:43,558 primer_db.views INFO     SNPs detected in primer
2019-12-06 14:40:43,560 primer_db.views INFO     Status of primer2: On order
2019-12-06 14:40:43,574 primer_db.views INFO     New coordinates added to db: 19 35773603 35773621 35282700 35282718
2019-12-06 14:40:43,578 primer_db.views INFO     Created primer: 2289 hamp_test_r
2019-12-06 14:40:43,578 primer_db.views INFO     Primer gene: HAMP
2019-12-06 14:40:43,578 primer_db.views INFO     Primer sequence: GCTCTCCCATCCCTGCTG
2019-12-06 14:40:43,580 primer_db.views INFO     Primer gc %: 66.67
2019-12-06 14:40:43,581 primer_db.views INFO     Primer tm: 59.490084
2019-12-06 14:43:27,657 primer_db.views INFO     Data submitted by scientist:
2019-12-06 14:43:27,684 primer_db.views INFO     Submitting primer
2019-12-06 14:43:28,083 primer_db.views INFO     Common info for primers:
2019-12-06 14:43:28,087 primer_db.views INFO     Pair created, id: 1407
2019-12-06 14:43:28,091 primer_db.views INFO     New scientist added to db: Science Person
2019-12-06 14:43:28,092 primer_db.views INFO     Using pcr program: TD65_55
2019-12-06 14:43:28,095 primer_db.views INFO     Using buffer: Buffer D
2019-12-06 14:43:28,097 primer_db.views INFO     Data for primer1:
2019-12-06 14:43:28,100 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:43:29,645 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:43:30,071 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:43:31,727 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:43:31,962 primer_db.views INFO     SNPs detected in primer
2019-12-06 14:43:31,963 primer_db.views INFO     Status of primer: On order
2019-12-06 14:43:31,968 primer_db.views INFO     New coordinates added to db: 2 179528048 179528066 178663321 178663339
2019-12-06 14:43:31,970 primer_db.views INFO     Created primer: 2290 ttn_test_f
2019-12-06 14:43:31,974 primer_db.views INFO     Primer gene: TTN
2019-12-06 14:43:31,983 primer_db.views INFO     Primer sequence: tgtaaaacgacggccagtTGGGACAGCTGCCTTTGG
2019-12-06 14:43:32,001 primer_db.views INFO     Primer gc %: 55.56
2019-12-06 14:43:32,007 primer_db.views INFO     Primer tm: 75.307668
2019-12-06 14:43:32,016 primer_db.views INFO     Data for primer2
2019-12-06 14:43:32,027 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:43:33,381 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:43:35,008 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:43:35,871 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:43:36,233 primer_db.views INFO     No SNPs detected in primer
2019-12-06 14:43:36,234 primer_db.views INFO     Status of primer2: On order
2019-12-06 14:43:36,250 primer_db.views INFO     New coordinates added to db: 2 179524290 179524310 178659563 178659583
2019-12-06 14:43:36,252 primer_db.views INFO     Created primer: 2291 ttn_test_r
2019-12-06 14:43:36,257 primer_db.views INFO     Primer gene: TTN
2019-12-06 14:43:36,257 primer_db.views INFO     Primer sequence: ACTGGCTGTGGGTTTGTCAT
2019-12-06 14:43:36,266 primer_db.views INFO     Primer gc %: 50.0
2019-12-06 14:43:36,275 primer_db.views INFO     Primer tm: 59.814099
2019-12-06 14:43:43,579 django.request ERROR    Internal Server Error: /primer_db/submit_pair/
Traceback (most recent call last):
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/storage/home/rainfoj/Projects/genetics_ark_django/primer_db/views.py", line 764, in submit_pair
    multiple_mapping(sequence1, sequence2, gene_chrom)
  File "/mnt/storage/home/rainfoj/Projects/genetics_ark_django/primer_db/views.py", line 150, in multiple_mapping
    if new_primer1.comments1 or new_primer2.comments2:
NameError: name 'new_primer1' is not defined
2019-12-06 14:43:43,983 django.request WARNING  Not Found: /favicon.ico
2019-12-06 14:45:45,354 primer_db.views INFO     Data submitted by scientist:
2019-12-06 14:45:45,384 primer_db.views INFO     Submitting primer
2019-12-06 14:45:45,588 primer_db.views INFO     Common info for primers:
2019-12-06 14:45:45,591 primer_db.views INFO     Pair created, id: 1408
2019-12-06 14:45:45,594 primer_db.views INFO     Scientist submitting primer: Science Person
2019-12-06 14:45:45,595 primer_db.views INFO     Using pcr program: TD65_55
2019-12-06 14:45:45,597 primer_db.views INFO     Using buffer: Buffer D
2019-12-06 14:45:45,598 primer_db.views INFO     Data for primer1:
2019-12-06 14:45:45,602 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:45:46,959 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:45:49,898 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:45:50,860 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:45:51,114 primer_db.views INFO     SNPs detected in primer
2019-12-06 14:45:51,116 primer_db.views INFO     Status of primer: On order
2019-12-06 14:45:51,128 primer_db.views INFO     Using coordinates: 2 179528048 179528066 178663321 178663339
2019-12-06 14:45:51,132 django.request ERROR    Internal Server Error: /primer_db/submit_pair/
Traceback (most recent call last):
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/mnt/storage/home/kimy/software/miniconda3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/mnt/storage/home/kimy/software/miniconda3/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/mnt/storage/home/kimy/software/miniconda3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/mnt/storage/home/kimy/software/miniconda3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/mnt/storage/home/kimy/software/miniconda3/lib/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.IntegrityError: (1062, "Duplicate entry 'ttn_test_f' for key 'name'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/storage/home/rainfoj/Projects/genetics_ark_django/primer_db/views.py", line 706, in submit_pair
    snp_status = snp_status1, snp_info = ";".join(snp_info1), snp_date = snp_date1
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/db/models/base.py", line 807, in save
    force_update=force_update, update_fields=update_fields)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/db/models/base.py", line 837, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/db/models/base.py", line 923, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/db/models/base.py", line 962, in _do_insert
    using=using, raw=raw)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1107, in execute_sql
    cursor.execute(sql, params)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/db/backends/utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/mnt/storage/home/kimy/software/miniconda3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 255, in execute
    self.errorhandler(self, exc, value)
  File "/mnt/storage/home/kimy/software/miniconda3/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/mnt/storage/home/kimy/software/miniconda3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 252, in execute
    res = self._query(query)
  File "/mnt/storage/home/kimy/software/miniconda3/lib/python3.6/site-packages/MySQLdb/cursors.py", line 378, in _query
    db.query(q)
  File "/mnt/storage/home/kimy/software/miniconda3/lib/python3.6/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1062, "Duplicate entry 'ttn_test_f' for key 'name'")
2019-12-06 14:46:01,967 primer_db.views INFO     Data submitted by scientist:
2019-12-06 14:46:01,992 primer_db.views INFO     Submitting primer
2019-12-06 14:46:02,183 primer_db.views INFO     Common info for primers:
2019-12-06 14:46:02,186 primer_db.views INFO     Pair created, id: 1409
2019-12-06 14:46:02,188 primer_db.views INFO     Scientist submitting primer: Science Person
2019-12-06 14:46:02,189 primer_db.views INFO     Using pcr program: TD65_55
2019-12-06 14:46:02,190 primer_db.views INFO     Using buffer: Buffer D
2019-12-06 14:46:02,191 primer_db.views INFO     Data for primer1:
2019-12-06 14:46:02,193 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:46:03,576 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:46:04,989 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:46:05,832 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:46:06,037 primer_db.views INFO     SNPs detected in primer
2019-12-06 14:46:06,038 primer_db.views INFO     Status of primer: On order
2019-12-06 14:46:06,041 primer_db.views INFO     Using coordinates: 2 179528048 179528066 178663321 178663339
2019-12-06 14:46:06,043 primer_db.views INFO     Created primer: 2293 ttn_test_f2
2019-12-06 14:46:06,053 primer_db.views INFO     Primer gene: TTN
2019-12-06 14:46:06,054 primer_db.views INFO     Primer sequence: tgtaaaacgacggccagtTGGGACAGCTGCCTTTGG
2019-12-06 14:46:06,056 primer_db.views INFO     Primer gc %: 55.56
2019-12-06 14:46:06,056 primer_db.views INFO     Primer tm: 75.307668
2019-12-06 14:46:06,056 primer_db.views INFO     Data for primer2
2019-12-06 14:46:06,059 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:46:07,337 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:46:09,287 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:46:10,144 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:46:10,358 primer_db.views INFO     No SNPs detected in primer
2019-12-06 14:46:10,360 primer_db.views INFO     Status of primer2: On order
2019-12-06 14:46:10,362 primer_db.views INFO     Using coordinates: 2 179524290 179524310 178659563 178659583
2019-12-06 14:46:10,364 primer_db.views INFO     Created primer: 2294 ttn_test_r2
2019-12-06 14:46:10,365 primer_db.views INFO     Primer gene: TTN
2019-12-06 14:46:10,366 primer_db.views INFO     Primer sequence: ACTGGCTGTGGGTTTGTCAT
2019-12-06 14:46:10,384 primer_db.views INFO     Primer gc %: 50.0
2019-12-06 14:46:10,386 primer_db.views INFO     Primer tm: 59.814099
2019-12-06 14:46:15,912 django.request ERROR    Internal Server Error: /primer_db/submit_pair/
Traceback (most recent call last):
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/storage/home/rainfoj/Projects/genetics_ark_django/primer_db/views.py", line 764, in submit_pair
    multiple_mapping(new_primer1, new_primer2, sequence1, sequence2, gene_chrom)
  File "/mnt/storage/home/rainfoj/Projects/genetics_ark_django/primer_db/views.py", line 150, in multiple_mapping
    if new_primer1.comments1 or new_primer2.comments2:
AttributeError: 'PrimerDetails' object has no attribute 'comments1'
2019-12-06 14:47:29,367 primer_db.views INFO     Data submitted by scientist:
2019-12-06 14:47:29,395 primer_db.views INFO     Submitting primer
2019-12-06 14:47:29,788 primer_db.views INFO     Common info for primers:
2019-12-06 14:47:29,792 primer_db.views INFO     Pair created, id: 1410
2019-12-06 14:47:29,796 primer_db.views INFO     Scientist submitting primer: Science Person
2019-12-06 14:47:29,797 primer_db.views INFO     Using pcr program: TD65_55
2019-12-06 14:47:29,799 primer_db.views INFO     Using buffer: Buffer D
2019-12-06 14:47:29,800 primer_db.views INFO     Data for primer1:
2019-12-06 14:47:29,832 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:47:31,290 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:47:31,663 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:47:32,593 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:47:32,767 primer_db.views INFO     SNPs detected in primer
2019-12-06 14:47:32,768 primer_db.views INFO     Status of primer: On order
2019-12-06 14:47:32,779 primer_db.views INFO     Using coordinates: 2 179528048 179528066 178663321 178663339
2019-12-06 14:47:32,781 primer_db.views INFO     Created primer: 2295 ttn_test_f3
2019-12-06 14:47:32,781 primer_db.views INFO     Primer gene: TTN
2019-12-06 14:47:32,781 primer_db.views INFO     Primer sequence: tgtaaaacgacggccagtTGGGACAGCTGCCTTTGG
2019-12-06 14:47:32,783 primer_db.views INFO     Primer gc %: 55.56
2019-12-06 14:47:32,784 primer_db.views INFO     Primer tm: 75.307668
2019-12-06 14:47:32,784 primer_db.views INFO     Data for primer2
2019-12-06 14:47:32,787 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:47:34,092 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:47:36,931 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:47:37,854 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:47:38,056 primer_db.views INFO     No SNPs detected in primer
2019-12-06 14:47:38,058 primer_db.views INFO     Status of primer2: On order
2019-12-06 14:47:38,061 primer_db.views INFO     Using coordinates: 2 179524290 179524310 178659563 178659583
2019-12-06 14:47:38,063 primer_db.views INFO     Created primer: 2296 ttn_test_r3
2019-12-06 14:47:38,063 primer_db.views INFO     Primer gene: TTN
2019-12-06 14:47:38,063 primer_db.views INFO     Primer sequence: ACTGGCTGTGGGTTTGTCAT
2019-12-06 14:47:38,065 primer_db.views INFO     Primer gc %: 50.0
2019-12-06 14:47:38,067 primer_db.views INFO     Primer tm: 59.814099
2019-12-06 14:50:06,642 primer_db.views INFO     Data submitted by scientist:
2019-12-06 14:50:06,677 primer_db.views INFO     Submitting primer
2019-12-06 14:50:06,884 primer_db.views INFO     Common info for primers:
2019-12-06 14:50:06,888 primer_db.views INFO     Pair created, id: 1411
2019-12-06 14:50:06,891 primer_db.views INFO     Scientist submitting primer: Science Person
2019-12-06 14:50:06,893 primer_db.views INFO     Using pcr program: TD65_55
2019-12-06 14:50:06,904 primer_db.views INFO     Using buffer: Buffer D
2019-12-06 14:50:06,904 primer_db.views INFO     Data for primer1:
2019-12-06 14:50:06,909 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:50:08,280 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:50:08,597 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:50:09,442 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:50:09,703 primer_db.views INFO     SNPs detected in primer
2019-12-06 14:50:09,705 primer_db.views INFO     Status of primer: On order
2019-12-06 14:50:09,709 primer_db.views INFO     Using coordinates: 2 179528048 179528066 178663321 178663339
2019-12-06 14:50:09,711 primer_db.views INFO     Created primer: 2297 ttn_test_f4
2019-12-06 14:50:09,712 primer_db.views INFO     Primer gene: TTN
2019-12-06 14:50:09,712 primer_db.views INFO     Primer sequence: tgtaaaacgacggccagtTGGGACAGCTGCCTTTGG
2019-12-06 14:50:09,713 primer_db.views INFO     Primer gc %: 55.56
2019-12-06 14:50:09,715 primer_db.views INFO     Primer tm: 75.307668
2019-12-06 14:50:09,715 primer_db.views INFO     Data for primer2
2019-12-06 14:50:09,718 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:50:11,093 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:50:11,562 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:50:12,415 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:50:12,581 primer_db.views INFO     No SNPs detected in primer
2019-12-06 14:50:12,583 primer_db.views INFO     Status of primer2: On order
2019-12-06 14:50:12,585 primer_db.views INFO     Using coordinates: 2 179524290 179524310 178659563 178659583
2019-12-06 14:50:12,588 primer_db.views INFO     Created primer: 2298 ttn_test_r4
2019-12-06 14:50:12,588 primer_db.views INFO     Primer gene: TTN
2019-12-06 14:50:12,588 primer_db.views INFO     Primer sequence: ACTGGCTGTGGGTTTGTCAT
2019-12-06 14:50:12,590 primer_db.views INFO     Primer gc %: 50.0
2019-12-06 14:50:12,591 primer_db.views INFO     Primer tm: 59.814099
2019-12-06 14:50:17,763 django.request ERROR    Internal Server Error: /primer_db/submit_pair/
Traceback (most recent call last):
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/storage/home/rainfoj/Projects/genetics_ark_django/primer_db/views.py", line 764, in submit_pair
    multiple_mapping(new_primer1, new_primer2, sequence1, sequence2, gene_chrom)
  File "/mnt/storage/home/rainfoj/Projects/genetics_ark_django/primer_db/views.py", line 153, in multiple_mapping
    new_primer1.update(new_primer1.comments + "\n Multiple mapping detected, check before use")
AttributeError: 'PrimerDetails' object has no attribute 'update'
2019-12-06 14:59:17,552 primer_db.views INFO     Data submitted by scientist:
2019-12-06 14:59:17,582 primer_db.views INFO     Submitting primer
2019-12-06 14:59:17,767 primer_db.views INFO     Common info for primers:
2019-12-06 14:59:17,771 primer_db.views INFO     Pair created, id: 1412
2019-12-06 14:59:17,774 primer_db.views INFO     Scientist submitting primer: Science Person
2019-12-06 14:59:17,776 primer_db.views INFO     Using pcr program: TD65_55
2019-12-06 14:59:17,777 primer_db.views INFO     Using buffer: Buffer D
2019-12-06 14:59:17,778 primer_db.views INFO     Data for primer1:
2019-12-06 14:59:17,783 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:59:19,292 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:59:19,731 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:59:20,621 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:59:20,790 primer_db.views INFO     SNPs detected in primer
2019-12-06 14:59:20,791 primer_db.views INFO     Status of primer: On order
2019-12-06 14:59:20,795 primer_db.views INFO     Using coordinates: 2 179528048 179528066 178663321 178663339
2019-12-06 14:59:20,804 primer_db.views INFO     Created primer: 2301 ttn_test_f5
2019-12-06 14:59:20,804 primer_db.views INFO     Primer gene: TTN
2019-12-06 14:59:20,804 primer_db.views INFO     Primer sequence: tgtaaaacgacggccagtTGGGACAGCTGCCTTTGG
2019-12-06 14:59:20,806 primer_db.views INFO     Primer gc %: 55.56
2019-12-06 14:59:20,807 primer_db.views INFO     Primer tm: 75.307668
2019-12-06 14:59:20,807 primer_db.views INFO     Data for primer2
2019-12-06 14:59:20,810 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:59:22,147 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:59:22,704 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 14:59:23,598 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 14:59:23,898 primer_db.views INFO     No SNPs detected in primer
2019-12-06 14:59:23,900 primer_db.views INFO     Status of primer2: On order
2019-12-06 14:59:23,902 primer_db.views INFO     Using coordinates: 2 179524290 179524310 178659563 178659583
2019-12-06 14:59:23,910 primer_db.views INFO     Created primer: 2302 ttn_test_r5
2019-12-06 14:59:23,910 primer_db.views INFO     Primer gene: TTN
2019-12-06 14:59:23,910 primer_db.views INFO     Primer sequence: ACTGGCTGTGGGTTTGTCAT
2019-12-06 14:59:23,912 primer_db.views INFO     Primer gc %: 50.0
2019-12-06 14:59:23,913 primer_db.views INFO     Primer tm: 59.814099
2019-12-06 15:03:33,308 primer_db.views INFO     Data submitted by scientist:
2019-12-06 15:03:33,340 primer_db.views INFO     Submitting primer
2019-12-06 15:03:33,527 primer_db.views INFO     Common info for primers:
2019-12-06 15:03:33,531 primer_db.views INFO     Pair created, id: 1413
2019-12-06 15:03:33,535 primer_db.views INFO     New scientist added to db: Science Science
2019-12-06 15:03:33,536 primer_db.views INFO     Using pcr program: TD65_55
2019-12-06 15:03:33,538 primer_db.views INFO     Using buffer: Buffer D
2019-12-06 15:03:33,539 primer_db.views INFO     Data for primer1:
2019-12-06 15:03:33,544 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 15:03:35,338 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 15:03:35,783 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 15:03:36,780 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 15:03:37,236 primer_db.views INFO     No SNPs detected in primer
2019-12-06 15:03:37,238 primer_db.views INFO     Status of primer: On order
2019-12-06 15:03:37,249 primer_db.views INFO     New coordinates added to db: 2 179511007 179511027 178646280 178646300
2019-12-06 15:03:37,258 primer_db.views INFO     Created primer: 2303 ttn_test_f_8
2019-12-06 15:03:37,259 primer_db.views INFO     Primer gene: TTN
2019-12-06 15:03:37,259 primer_db.views INFO     Primer sequence: tgtaaaacgacggccagtACAAAGCATCCAGACAAGCC
2019-12-06 15:03:37,260 primer_db.views INFO     Primer gc %: 50.0
2019-12-06 15:03:37,262 primer_db.views INFO     Primer tm: 73.421895
2019-12-06 15:03:37,262 primer_db.views INFO     Data for primer2
2019-12-06 15:03:37,265 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 15:03:38,696 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 15:03:39,335 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 15:03:40,723 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 15:03:40,920 primer_db.views INFO     No SNPs detected in primer
2019-12-06 15:03:40,922 primer_db.views INFO     Status of primer2: On order
2019-12-06 15:03:40,926 primer_db.views INFO     New coordinates added to db: 2 179511535 179511557 178646808 178646830
2019-12-06 15:03:40,933 primer_db.views INFO     Created primer: 2304 ttn_test_r_8
2019-12-06 15:03:40,934 primer_db.views INFO     Primer gene: TTN
2019-12-06 15:03:40,935 primer_db.views INFO     Primer sequence: GGAATAATTGCCTTGGATCCTC
2019-12-06 15:03:40,937 primer_db.views INFO     Primer gc %: 45.45
2019-12-06 15:03:40,937 primer_db.views INFO     Primer tm: 56.873035
2019-12-06 15:05:13,539 primer_db.views INFO     Data submitted by scientist:
2019-12-06 15:05:13,571 primer_db.views INFO     Submitting primer
2019-12-06 15:05:13,988 primer_db.views INFO     Common info for primers:
2019-12-06 15:05:13,992 primer_db.views INFO     Pair created, id: 1414
2019-12-06 15:05:13,998 primer_db.views INFO     New scientist added to db: Primer Guy
2019-12-06 15:05:13,999 primer_db.views INFO     Using pcr program: TD65_55
2019-12-06 15:05:14,001 primer_db.views INFO     Using buffer: Buffer D
2019-12-06 15:05:14,001 primer_db.views INFO     Data for primer1:
2019-12-06 15:05:14,007 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 15:05:15,327 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 15:05:15,620 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 15:05:16,478 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 15:05:16,820 primer_db.views INFO     SNPs detected in primer
2019-12-06 15:05:16,821 primer_db.views INFO     Status of primer: On order
2019-12-06 15:05:16,830 primer_db.views INFO     New coordinates added to db: 2 179400103 179400125 178535376 178535398
2019-12-06 15:05:16,839 primer_db.views INFO     Created primer: 2305 TTN_F
2019-12-06 15:05:16,839 primer_db.views INFO     Primer gene: TTN
2019-12-06 15:05:16,839 primer_db.views INFO     Primer sequence: tgtaaaacgacggccagtAACGTGTTTCTCGGGCCTGTCC
2019-12-06 15:05:16,841 primer_db.views INFO     Primer gc %: 55.0
2019-12-06 15:05:16,842 primer_db.views INFO     Primer tm: 76.212097
2019-12-06 15:05:16,842 primer_db.views INFO     Data for primer2
2019-12-06 15:05:16,845 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 15:05:18,150 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 15:05:18,713 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 15:05:19,530 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 15:05:19,784 primer_db.views INFO     SNPs detected in primer
2019-12-06 15:05:19,786 primer_db.views INFO     Status of primer2: On order
2019-12-06 15:05:19,796 primer_db.views INFO     New coordinates added to db: 2 179400504 179400525 178535777 178535798
2019-12-06 15:05:19,803 primer_db.views INFO     Created primer: 2306 TTN_R
2019-12-06 15:05:19,804 primer_db.views INFO     Primer gene: TTN
2019-12-06 15:05:19,804 primer_db.views INFO     Primer sequence: ATGCTCTCCGAGGTGAAGTGG
2019-12-06 15:05:19,805 primer_db.views INFO     Primer gc %: 57.14
2019-12-06 15:05:19,807 primer_db.views INFO     Primer tm: 61.842810
2019-12-06 15:10:09,273 django.request ERROR    Internal Server Error: /primer_db/submit_pair/
Traceback (most recent call last):
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/utils/datastructures.py", line 83, in __getitem__
    list_ = super(MultiValueDict, self).__getitem__(key)
KeyError: 'form1-gene'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/storage/home/rainfoj/Projects/genetics_ark_django/primer_db/views.py", line 569, in submit_pair
    data["form2-gene"] = data["form1-gene"]
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
django.utils.datastructures.MultiValueDictKeyError: "'form1-gene'"
2019-12-06 15:11:21,803 django.request ERROR    Internal Server Error: /primer_db/submit_pair/
Traceback (most recent call last):
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/utils/datastructures.py", line 83, in __getitem__
    list_ = super(MultiValueDict, self).__getitem__(key)
KeyError: 'form1-gene'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/storage/home/rainfoj/Projects/genetics_ark_django/primer_db/views.py", line 570, in submit_pair
    data["form2-gene"] = data["form1-gene"]
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
django.utils.datastructures.MultiValueDictKeyError: "'form1-gene'"
2019-12-06 15:11:32,294 django.request ERROR    Internal Server Error: /primer_db/submit_pair/
Traceback (most recent call last):
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/utils/datastructures.py", line 83, in __getitem__
    list_ = super(MultiValueDict, self).__getitem__(key)
KeyError: 'form1-gene'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/storage/home/rainfoj/Projects/genetics_ark_django/primer_db/views.py", line 570, in submit_pair
    data["form2-gene"] = data["form1-gene"]
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
django.utils.datastructures.MultiValueDictKeyError: "'form1-gene'"
2019-12-06 15:11:48,937 django.request ERROR    Internal Server Error: /primer_db/submit_pair/
Traceback (most recent call last):
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/utils/datastructures.py", line 83, in __getitem__
    list_ = super(MultiValueDict, self).__getitem__(key)
KeyError: 'form1-gene'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/storage/home/rainfoj/Projects/genetics_ark_django/primer_db/views.py", line 570, in submit_pair
    data["form2-gene"] = data["form1-gene"]
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
django.utils.datastructures.MultiValueDictKeyError: "'form1-gene'"
2019-12-06 15:13:59,009 django.request ERROR    Internal Server Error: /primer_db/submit_pair/
Traceback (most recent call last):
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/utils/datastructures.py", line 83, in __getitem__
    list_ = super(MultiValueDict, self).__getitem__(key)
KeyError: 'form1-gene'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/storage/home/rainfoj/Projects/genetics_ark_django/primer_db/views.py", line 570, in submit_pair
    data["form2-gene"] = data["form1-gene"]
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
django.utils.datastructures.MultiValueDictKeyError: "'form1-gene'"
2019-12-06 15:34:06,453 django.request ERROR    Internal Server Error: /primer_db/submit_pair/
Traceback (most recent call last):
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/utils/datastructures.py", line 83, in __getitem__
    list_ = super(MultiValueDict, self).__getitem__(key)
KeyError: 'form1-gene'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/storage/home/rainfoj/Projects/genetics_ark_django/primer_db/views.py", line 575, in submit_pair
    data["form2-gene"] = data["form1-gene"]
  File "/mnt/storage/apps/software/django/1.11.5/lib/python2.7/site-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
django.utils.datastructures.MultiValueDictKeyError: "'form1-gene'"
2019-12-06 15:34:56,519 primer_db.views INFO     Data submitted by scientist:
2019-12-06 15:34:56,599 primer_db.views INFO     Submitting primer
2019-12-06 15:34:56,814 primer_db.views INFO     Common info for primers:
2019-12-06 15:34:56,817 primer_db.views INFO     Pair created, id: 1417
2019-12-06 15:34:56,820 primer_db.views INFO     New scientist added to db: Primer Primer
2019-12-06 15:34:56,832 primer_db.views INFO     Using pcr program: TD65_55
2019-12-06 15:34:56,833 primer_db.views INFO     Using buffer: Buffer D
2019-12-06 15:34:56,840 primer_db.views INFO     Data for primer1:
2019-12-06 15:34:56,853 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 15:34:58,617 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 15:34:59,106 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 15:35:00,027 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 15:35:00,246 primer_db.views INFO     SNPs detected in primer
2019-12-06 15:35:00,248 primer_db.views INFO     Status of primer: On order
2019-12-06 15:35:00,252 primer_db.views INFO     New coordinates added to db: 2 179396531 179396551 178531804 178531824
2019-12-06 15:35:00,265 primer_db.views INFO     Created primer: 2311 primer_f
2019-12-06 15:35:00,266 primer_db.views INFO     Primer gene: TTN
2019-12-06 15:35:00,266 primer_db.views INFO     Primer sequence: tgtaaaacgacggccagtTGTGAAAGGCTGCTGACTCA
2019-12-06 15:35:00,273 primer_db.views INFO     Primer gc %: 50.0
2019-12-06 15:35:00,282 primer_db.views INFO     Primer tm: 74.330685
2019-12-06 15:35:00,290 primer_db.views INFO     Data for primer2
2019-12-06 15:35:00,301 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 15:35:01,951 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 15:35:02,276 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 15:35:03,137 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 15:35:03,335 primer_db.views INFO     SNPs detected in primer
2019-12-06 15:35:03,337 primer_db.views INFO     Status of primer2: On order
2019-12-06 15:35:03,340 primer_db.views INFO     New coordinates added to db: 2 179397009 179397029 178532282 178532302
2019-12-06 15:35:03,355 primer_db.views INFO     Created primer: 2312 primer_r
2019-12-06 15:35:03,359 primer_db.views INFO     Primer gene: TTN
2019-12-06 15:35:03,360 primer_db.views INFO     Primer sequence: AGAGTTGCTTCGCCCAGTTA
2019-12-06 15:35:03,403 primer_db.views INFO     Primer gc %: 50.0
2019-12-06 15:35:03,407 primer_db.views INFO     Primer tm: 59.314903
2019-12-06 15:38:31,915 primer_db.views INFO     Data submitted by scientist:
2019-12-06 15:38:31,939 primer_db.views INFO     Submitting primer
2019-12-06 15:38:32,431 primer_db.views INFO     Common info for primers:
2019-12-06 15:38:32,435 primer_db.views INFO     Pair created, id: 1418
2019-12-06 15:38:32,438 primer_db.views INFO     New scientist added to db: Kqjg Kljh
2019-12-06 15:38:32,453 primer_db.views INFO     Using pcr program: TD65_55
2019-12-06 15:38:32,461 primer_db.views INFO     Using buffer: Buffer D
2019-12-06 15:38:32,469 primer_db.views INFO     Data for primer1:
2019-12-06 15:38:32,481 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 15:38:33,994 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 15:38:34,496 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 15:38:35,515 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 15:38:35,773 primer_db.views INFO     SNPs detected in primer
2019-12-06 15:38:35,775 primer_db.views INFO     Status of primer: On order
2019-12-06 15:38:35,794 primer_db.views INFO     Using coordinates: 2 179528048 179528066 178663321 178663339
2019-12-06 15:38:35,801 primer_db.views INFO     Created primer: 2313 ttn2f
2019-12-06 15:38:35,802 primer_db.views INFO     Primer gene: TTN
2019-12-06 15:38:35,810 primer_db.views INFO     Primer sequence: tgtaaaacgacggccagtTGGGACAGCTGCCTTTGG
2019-12-06 15:38:35,819 primer_db.views INFO     Primer gc %: 55.56
2019-12-06 15:38:35,828 primer_db.views INFO     Primer tm: 75.307668
2019-12-06 15:38:35,835 primer_db.views INFO     Data for primer2
2019-12-06 15:38:35,838 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 15:38:37,645 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 15:38:40,254 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 15:38:41,159 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 15:38:41,549 primer_db.views INFO     No SNPs detected in primer
2019-12-06 15:38:41,551 primer_db.views INFO     Status of primer2: On order
2019-12-06 15:38:41,553 primer_db.views INFO     Using coordinates: 2 179524290 179524310 178659563 178659583
2019-12-06 15:38:41,562 primer_db.views INFO     Created primer: 2314 ttn2r
2019-12-06 15:38:41,569 primer_db.views INFO     Primer gene: TTN
2019-12-06 15:38:41,577 primer_db.views INFO     Primer sequence: ACTGGCTGTGGGTTTGTCAT
2019-12-06 15:38:41,586 primer_db.views INFO     Primer gc %: 50.0
2019-12-06 15:38:41,594 primer_db.views INFO     Primer tm: 59.814099
2019-12-06 15:41:48,062 primer_db.views INFO     Data submitted by scientist:
2019-12-06 15:41:48,133 primer_db.views INFO     Submitting primer
2019-12-06 15:41:48,353 primer_db.views INFO     Common info for primers:
2019-12-06 15:41:48,357 primer_db.views INFO     Pair created, id: 1419
2019-12-06 15:41:48,362 primer_db.views INFO     New scientist added to db: Man Science
2019-12-06 15:41:48,481 primer_db.views INFO     Using pcr program: TD65_55
2019-12-06 15:41:48,483 primer_db.views INFO     Using buffer: Buffer D
2019-12-06 15:41:48,498 primer_db.views INFO     Data for primer1:
2019-12-06 15:41:48,511 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 15:41:49,895 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 15:41:50,328 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 15:41:51,228 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 15:41:51,488 primer_db.views INFO     SNPs detected in primer
2019-12-06 15:41:51,489 primer_db.views INFO     Status of primer: On order
2019-12-06 15:41:51,508 primer_db.views INFO     Using coordinates: 2 179528048 179528066 178663321 178663339
2019-12-06 15:41:51,527 primer_db.views INFO     Created primer: 2315 ttnf3
2019-12-06 15:41:51,527 primer_db.views INFO     Primer gene: TTN
2019-12-06 15:41:51,527 primer_db.views INFO     Primer sequence: tgtaaaacgacggccagtTGGGACAGCTGCCTTTGG
2019-12-06 15:41:51,531 primer_db.views INFO     Primer gc %: 55.56
2019-12-06 15:41:51,539 primer_db.views INFO     Primer tm: 75.307668
2019-12-06 15:41:51,547 primer_db.views INFO     Data for primer2
2019-12-06 15:41:51,558 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 15:41:52,917 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 15:41:53,225 urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): gnomad.broadinstitute.org:443
2019-12-06 15:41:54,074 urllib3.connectionpool DEBUG    https://gnomad.broadinstitute.org:443 "POST /api HTTP/1.1" 200 None
2019-12-06 15:41:54,355 primer_db.views INFO     No SNPs detected in primer
2019-12-06 15:41:54,357 primer_db.views INFO     Status of primer2: On order
2019-12-06 15:41:54,360 primer_db.views INFO     Using coordinates: 2 179524290 179524310 178659563 178659583
2019-12-06 15:41:54,392 primer_db.views INFO     Created primer: 2316 ttnr3
2019-12-06 15:41:54,396 primer_db.views INFO     Primer gene: TTN
2019-12-06 15:41:54,398 primer_db.views INFO     Primer sequence: ACTGGCTGTGGGTTTGTCAT
2019-12-06 15:41:54,406 primer_db.views INFO     Primer gc %: 50.0
2019-12-06 15:41:54,414 primer_db.views INFO     Primer tm: 59.814099
2019-12-06 15:56:21,757 django.request WARNING  Not Found: /primer_db/help
2019-12-06 15:56:21,860 django.request WARNING  Not Found: /favicon.ico
